// Code generated by mockery v2.36.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UserSetter is an autogenerated mock type for the UserSetter type
type UserSetter struct {
	mock.Mock
}

// UserSetter provides a mock function with given fields: ctx, user, password, id
func (_m *UserSetter) UserSetter(ctx context.Context, user string, password string, id string) error {
	ret := _m.Called(ctx, user, password, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, user, password, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserSetter creates a new instance of UserSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSetter {
	mock := &UserSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
